package conn;


/**
* conn/Conn.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Conn.idl
* Segunda-feira, 3 de Junho de 2019 23h25min04s BRT
*/

public interface Conn extends ConnOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Conn
